### PR TITLE
message from baaber

### PR DESCRIPTION
**Pull request by CodeFish-CodeFish**

### CODE REVIEW

**Comment by K1n1t** [comment]
good job

**Review by iadgar-osmonov — COMMENTED** [review]
good job

**Review by azamat73 — COMMENTED** [review]
jarayt

**Review by nurjolone — APPROVED** [review]
ok looks ok.. But you can do better

**Review by azamat73 — APPROVED** [review]
jarayt

**Review by K1n1t — COMMENTED** [review]
nice

**Pull request merged**
