### PR TITLE
aza

### PR DESCRIPTION
**Pull request by azamat73**

### CODE REVIEW

**Review by CodeFish-CodeFish — APPROVED** [review]
comments

**Review by K1n1t — COMMENTED** [review]
bueno

**Comment by ValyaSenkiv** [comment]
fine

**Review by iadgar-osmonov — APPROVED** [review]
nu tak sebe

**Review by ValyaSenkiv — COMMENTED** [review]
good

**Review by nurjolone — APPROVED** [review]
great job man

**Pull request merged**
